name: Auto Update Zee Bangla M3U8

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_workflow]
  schedule:
    - cron: '*/5 * * * *'
    

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: python get_channel.py

      - name: Commit and Push Changes
        run: |
          touch zee-bangla.m3u8
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add zee-bangla.m3u8
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update Zee Bangla m3u8" && git push)
