name: Auto Update Channel Link Every 5 Mins

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: python get_channel.py

      - name: Commit and Push Changes
        run: |
          touch playlist.m3u8 stream.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u8 stream.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update M3U8 link" && git push)
